### ISSUE TITLE
Remove failure

### ISSUE THREAD

**Issue by datanel** [hove-io/transit_model#442]
Should we consider removing `failure` and having custom errors implementing https://doc.rust-lang.org/std/error/trait.Error.html ?

`failure` wraps errors implementing https://docs.rs/failure/0.1.6/failure/trait.Fail.html not https://doc.rust-lang.org/std/error/trait.Error.html

what we might do
- create erros with struct/enum 
- implement https://doc.rust-lang.org/std/error/trait.Error.html, we might use https://github.com/dtolnay/thiserror
- use https://github.com/dtolnay/anyhow

**Comment by woshilapin** [comment]
Sounds like a good idea. It'd be nice to experiment before taking a decision but I can see some limitations with the solution with have today (`failure`). Therefore, I'm curious about what you propose. Let's see if the situation would be better (I believe it would from what I read).

**Comment by woshilapin** [comment]
From [this survey on error-handlers in Rust](https://blog.yoshuawuyts.com/error-handling-survey/), it looks like `anyhow` is a serious solution to replace `failure`. One missing feature of `anyhow` is backtraces (but this should be soon solved since backtraces are part of Rust nightly and `anyhow` uses them). And `thiserror` seems like a very good candidate for structured errors.

These are [great](https://www.reddit.com/r/rust/comments/dzq42h/error_handling_survey/) [articles](https://lukaskalbertodt.github.io/2019/11/14/thoughts-on-error-handling-in-rust.html) on the topic.

I was planning on experimenting `anyhow` with `thiserror` in the near future, for example, converting one of our API fully to this new pattern (I was thinking of `transit_model::hellogo_fares::enrich_with_hellogo_fares`). Any objection?

**Comment by datanel** [comment]
`failure` was replaced by `anyhow` https://github.com/hove-io/transit_model/pull/829
